### ISSUE TITLE
Release 1.0.3 doesn't find module '@actions/core'

### ISSUE THREAD

**Issue by jheilgeist** [author/action-rollback#8]
Our builds broke shortly after the new release 1.0.3 arrived. I've tested the build with @stable, @1.0.0, and @1.0.3: @stable/@1.0.3 fail, while @1.0.0 works as expected.

How we use the action:
```
- name: Delete Previous Release
  uses: author/action-rollback@stable
  # step fails, if tag doesn't exist in the first place; but that's ok!
  continue-on-error: true
  with:
    tag: ${{ env.release_tag }}
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

How it fails with 1.0.3:
```
Run author/action-rollback@1.0.3
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/_actions/author/action-rollback/1.0.3/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/author/action-rollback/1.0.3/index.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/author/action-rollback/1.0.3/index.js'
  ]
}
```

**Comment by mukunku** [comment]
All my github actions broke because of this release :( Looks like its because the node_modules folder was removed. I know there's a way to get it to work without that folder but right now it seems like its not.

Also I created a tag-exists action just for this purpose @jheilgeist : https://github.com/marketplace/actions/tag-exists-action

**Comment by coreybutler** [comment]
I've just reverted the change. My apologies to those affected. It does look like it's just the missing dependency, but I'll update later (not this week) after I can test more thoroughly.
